'use client';

import { HeroSection, Button, GlassCard } from '@/components/ui';
import { motion } from 'framer-motion';
import Link from 'next/link';

const features = [
  {
    icon: '🎯',
    title: 'Tailored Topics',
    description: 'Choose from various topics or create your own'
  },
  {
    icon: '🤖',
    title: 'AI-Powered',
    description: 'Questions and feedback generated by AI'
  },
  {
    icon: '📊',
    title: 'Instant Results',
    description: 'Get detailed feedback and recommendations'
  }
];

export default function Home() {
  const containerVariants = {
    initial: { opacity: 0 },
    animate: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
      },
    },
  };

  const itemVariants = {
    initial: { opacity: 0, y: 20 },
    animate: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.5,
      },
    },
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-gray-50 dark:from-gray-900 dark:to-gray-800">
      <HeroSection
        title="Test Your Knowledge"
        description="Challenge yourself with our adaptive quiz experience powered by AI"
        className="pt-24"
      >
        <Link href="/quiz/start">
          <Button
            variant="primary"
            size="lg"
            className="text-lg px-8 py-4"
          >
            <span className="text-xl">✨</span> Start Quiz
          </Button>
        </Link>
      </HeroSection>

      {/* Features Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
        <motion.div
          variants={containerVariants}
          initial="initial"
          animate="animate"
          className="grid grid-cols-1 md:grid-cols-3 gap-8"
        >
          {features.map((feature, index) => (
            <motion.div key={index} variants={itemVariants}>
              <GlassCard className="h-full">
                <div className="text-center space-y-4">
                  <div className="text-4xl mb-4">{feature.icon}</div>
                  <h3 className="text-xl font-semibold dark:text-white">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600 dark:text-gray-300">
                    {feature.description}
                  </p>
                </div>
              </GlassCard>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </div>
  );
}