import { QuizLayout, Card, Button } from '@/components/ui';
import Link from 'next/link';

export default function Home() {
  return (
    <QuizLayout>
      <div className="min-h-screen flex items-center justify-center">
        <Card gradient className="max-w-2xl w-full mx-4">
          <div className="text-center space-y-8 py-12">
            <div className="space-y-4">
              <h1 className="text-4xl md:text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 to-purple-600">
                Test Your Knowledge
              </h1>
              <p className="text-lg md:text-xl text-gray-600 max-w-lg mx-auto">
                Challenge yourself with our adaptive quiz experience across various topics.
              </p>
            </div>
            
            <div className="flex justify-center">
              <Link href="/quiz/start">
                <Button variant="primary" size="lg" className="text-lg px-8 py-4">
                  Start Quiz
                </Button>
              </Link>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-3xl mx-auto mt-12">
              <div className="text-center p-4">
                <div className="mb-2">🎯</div>
                <h3 className="font-semibold mb-1">Tailored Topics</h3>
                <p className="text-gray-600 text-sm">Choose from various topics or create your own</p>
              </div>
              <div className="text-center p-4">
                <div className="mb-2">🤖</div>
                <h3 className="font-semibold mb-1">AI-Powered</h3>
                <p className="text-gray-600 text-sm">Questions and feedback generated by AI</p>
              </div>
              <div className="text-center p-4">
                <div className="mb-2">📊</div>
                <h3 className="font-semibold mb-1">Instant Results</h3>
                <p className="text-gray-600 text-sm">Get detailed feedback and recommendations</p>
              </div>
            </div>
          </div>
        </Card>
      </div>
    </QuizLayout>
  );
}